# frozen_string_literal: true

directories %w[config lib spec]

guard :rspec, cmd: 'bundle exec rspec' do
  require 'guard/rspec/dsl'
  dsl = Guard::RSpec::Dsl.new(self)

  # RSpec files
  rspec = dsl.rspec
  watch(rspec.spec_helper) { rspec.spec_dir }
  watch(rspec.spec_support) { rspec.spec_dir }
  watch(rspec.spec_files)

  # Ruby files
  ruby = dsl.ruby
  dsl.watch_spec_files_for(ruby.lib_files)

  # Related files
  watch('lib/plutil.rb') { 'spec/lib/webarchive_spec.rb' }
  %w[webarchive plutil].each do |unwebarchive_dependency|
    watch("lib/#{unwebarchive_dependency}.rb") { 'spec/lib/unwebarchive_spec.rb' }
  end
end
